### PR TITLE
Added Moreowners, fixed retrosign

### PR DESCRIPTION
**Pull request by DannyDB5544**
- Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility

- also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.

- Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.

- Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted. Nothing special other than that. Reboots the only way to undo the command currently, though the aim is to turn it into a config once issues with other cogs have been dealt with.

### CODE REVIEW

**Comment by MrMith** [comment]
> 
> 
>     * ```
>       Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
>       ```
> 
>     * ```
>       also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
>       ```
> 
>     * ```
>       Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
>       ```
> 
>     * ```
>       Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
>       ```

**Comment by MrMith** [comment]
> 
> 
> > ```
> > * ```
> >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> >   ```
> > 
> > * ```
> >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> >   ```
> > 
> > * ```
> >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> >   ```
> > 
> > * ```
> >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> >   ```
> > ```

**Comment by MrMith** [comment]
> 
> 
> > > ```
> > > * ```
> > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > ```
> > > 
> > > 
> > > 
> > > * ```
> > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > >   ```
> > > * ```
> > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > >   ```
> > > * ```
> > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > ```
> > > > * ```
> > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > ```
> > > > 
> > > > 
> > > > 
> > > > * ```
> > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > >   ```
> > > > * ```
> > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > >   ```
> > > > * ```
> > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > > ```
> > > > > * ```
> > > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > > ```
> > > > > 
> > > > > 
> > > > > 
> > > > > * ```
> > > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > > >   ```
> > > > > * ```
> > > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > > >   ```
> > > > > * ```
> > > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > > > ```
> > > > > > * ```
> > > > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > * ```
> > > > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > > > >   ```
> > > > > > * ```
> > > > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > > > >   ```
> > > > > > * ```
> > > > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > > > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > > > > ```
> > > > > > > * ```
> > > > > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > * ```
> > > > > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > > > > >   ```
> > > > > > > * ```
> > > > > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > > > > >   ```
> > > > > > > * ```
> > > > > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > > > > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > > > > > ```
> > > > > > > > * ```
> > > > > > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > * ```
> > > > > > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > > > > > >   ```
> > > > > > > > * ```
> > > > > > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > > > > > >   ```
> > > > > > > > * ```
> > > > > > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > > > > > >   ```

**Comment by MrMith** [comment]
> 
> 
> > > > > > > > > ```
> > > > > > > > > * ```
> > > > > > > > >   Warnings has had its Unicode emotes changed to Unicode escapes in the name of compatibility
> > > > > > > > > ```
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > * ```
> > > > > > > > >   also a bit of TLC in warnings. Its not perfect, and it won't fix everything, but progress is needed.
> > > > > > > > >   ```
> > > > > > > > > * ```
> > > > > > > > >   Retrosign was dead due to Black shoes. Undone Black shoes for retrosign, will keep an eye out for similar issues.
> > > > > > > > >   ```
> > > > > > > > > * ```
> > > > > > > > >   Added Moreowners, a way to remove the bottle neck of checking everything through one person while still allowing that person to have control (namely, by restarting the bot) Moreowners will grant the targeted user owner powers on the bot, until it is rebooted.
> > > > > > > > >   ```

**Comment by DannyDB5544** [comment]
**Added**

- Fixed LOA not being able to remove expired LOA's, get_message was changed to fetch_message.

**Comment by DannyDB5544** [comment]
Super Ping for Zabszk, MoreOwners changed to use Config go store owners in a better way.

**Comment by DannyDB5544** [comment]
Help messages have been added to commands, and fixed a minor spacing fault that would cause said help to look peculiar.

**Comment by DannyDB5544** [comment]
Reverted Warnings to its vanilla state. Plan will be to provide the Moderation team with basic **but working** system and then return the features that they needed but weren't working. Luckily, this isnt any huge changes - No longer embed, auto unwarns dont exist, and neither will VIP warnings. 
Plan will be to phase auto unwarning back in, then VIP unwarns, then embeds.

**Comment by DannyDB5544** [comment]
**Warnings Notice**
Identifier has been changed, we should be ok to let the existing warning file remain.

**Comment by DannyDB5544** [comment]
Filter has had its listeners and handling re-inserted to allow it more reliability. No changes will be required outside of this, testing confirmed it to work with existing filters.

**Pull request merged**
